### ISSUE TITLE
Cloudflare - Durable Object support

### ISSUE THREAD

**Issue by gwynhokkers** [nuxt-hub/core#223] opened 2024-08-09 09:40 UTC
Hi, I'm very much interested in NuxtHub and exploring some of its capabilities. In particular I'm interested in trying out using Durable Objects. The idea would be to take something like this [chat demo](https://github.com/cloudflare/workers-chat-demo) and create it with NuxtHub. Question at the moment would be, does NuxtHub support this currently, if so could someone point me in the right direction to get started, and if not what path could I take to create something that could?

I noticed this pull request #113 - am I right in thinking that if this is implemented, I will be able to impletement durable objects by extending the `wrangler.toml` and then create server api endpoints to handle the events (the functions in `/src/chat.mjs` in the demo). Or is there a way to already do this?

**Comment by atinux** [comment] 2024-08-11 18:58
Closing as duplicate of #50 

Yes it's planned! But today only Cloudflare Workers are supported for creating DO, right now NuxtHub only support Cloudflare Pages to deploy Nuxt apps to reduce cost (for static assets) but I know static assets are planned. Once it's good, the support for DO will move forward :)

**Closed by atinux** 2024-08-11 18:58 UTC
